name: rectangles
favicon: null
layout_spectrum: 0.6866937489248812
typography_spectrum: 0.928864779882133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#ffffff'
    - '#525252'
    - '#b4b4b4'
    - '#969696'
  brandStrength: 1
  lightness: 0.8856625033076853
  saturation: 0.581777579151094
  rhythmicContrast: 0.9639680271502584
purpose: []
