name: rectangles
favicon: null
layout_spectrum: 0.6866937489248812
typography_spectrum: 0.928864779882133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3146587163209915
  lightness: 0.8856625033076853
  saturation: 0.581777579151094
  rhythmicContrast: 0.9639680271502584
purpose: []
